### PR TITLE
Bumped dependency version on uvisor-lib

### PR DESCRIPTION
**Pull request by AlessandroA**
Requires https://github.com/ARMmbed/target-frdm-k64f-gcc/pull/11 to bu merged, bumped and published
@bremoran @0xc0170 @autopulated

### CODE REVIEW

**Comment by 0xc0170** [comment]
Let's wait for the target to be published, I merged it but can't publish at the moment. What about armcc target, is it functional with 0.8.0 uvisor?

**Comment by AlessandroA** [comment]
@0xc0170 armcc is not supported yet on uVisor, but PRs are coming soon for it.

Modules that depend on uVisor 0.8.0 and are built with armcc will use for the moment a compatibile fallback version of uvisor, so that compilation succeeds (with a warning on uvisor being disabled).

**Comment by autopulated** [comment]
gcc target update is published now.

**Comment by 0xc0170** [comment]
@autopulated Thanks, merging this and release new minor

**Pull request merged**
