### PR TITLE
Serial - removal of unused dma state

### PR DESCRIPTION
**Pull request by 0xc0170**
Removal of the deprecated code, no other changes here (diff here is not ideal as I can see).

@bogdanm @salkinium

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by bogdanm** [comment]
+1

**Comment by salkinium** [comment]
+1, tested in hardware using example-async-example.
Async Unittest is still failing though (#34).

**Pull request merged**
